export const tblHead = {
  columns: [
    {
      key: "id",
      label: "ID",
      sortable: true,
      filterable: false,
    },
    {
      key: "name",
      label: "Name",
      sortable: true,
      filterable: true,
    },
    {
      key: "email",
      label: "Email",
      sortable: true,
      filterable: true,
    },
    {
      key: "role",
      label: "Role",
      sortable: false,
      filterable: true,
    },
    {
      key: "status",
      label: "Status",
      sortable: true,
      filterable: true,
      render: "statusBadge",
    },
  ],
  pageSizeOptions: [5, 10, 20],
  defaultPageSize: 5,
};

export const tblData = {
  data: [
    {
      id: 1,
      name: "Alex Rivera",
      email: "alex.rivera@example.com",
      role: "Admin",
      status: "active",
    },
    {
      id: 2,
      name: "Jordan Chen",
      email: "j.chen@company.org",
      role: "Editor",
      status: "pending",
    },
    {
      id: 3,
      name: "Taylor Smith",
      email: "tsmith@service.net",
      role: "Viewer",
      status: "inactive",
    },
    {
      id: 4,
      name: "Morgan H.",
      email: "m.h@provider.io",
      role: "Admin",
      status: "active",
    },
    {
      id: 5,
      name: "Casey Blair",
      email: "cblair@studio.com",
      role: "Editor",
      status: "active",
    },
    {
      id: 6,
      name: "Riley Quinn",
      email: "rquinn@agency.co",
      role: "Viewer",
      status: "pending",
    },
    {
      id: 7,
      name: "Skyler Grey",
      email: "sgrey@webmail.com",
      role: "Editor",
      status: "inactive",
    },
    {
      id: 8,
      name: "Jamie Vance",
      email: "jvance@corp.com",
      role: "Admin",
      status: "active",
    },
    {
      id: 9,
      name: "Parker Lane",
      email: "plane@tech.org",
      role: "Viewer",
      status: "active",
    },
    {
      id: 10,
      name: "Dakota Reed",
      email: "dreed@data.io",
      role: "Editor",
      status: "pending",
    },
    {
      id: 11,
      name: "Sam Foster",
      email: "sfoster@cloud.net",
      role: "Admin",
      status: "inactive",
    },
    {
      id: 12,
      name: "Robin Banks",
      email: "rbanks@finance.com",
      role: "Viewer",
      status: "active",
    },
    {
      id: 13,
      name: "Avery Moss",
      email: "amoss@creative.biz",
      role: "Editor",
      status: "active",
    },
    {
      id: 14,
      name: "Peyton Hill",
      email: "phill@logistics.com",
      role: "Viewer",
      status: "pending",
    },
    {
      id: 15,
      name: "Drew Carey",
      email: "dcarey@media.tv",
      role: "Admin",
      status: "active",
    },
    {
      id: 16,
      name: "Quinn Fabray",
      email: "qfabray@high.edu",
      role: "Editor",
      status: "inactive",
    },
    {
      id: 17,
      name: "Blake Lively",
      email: "blively@cinema.com",
      role: "Viewer",
      status: "active",
    },
    {
      id: 18,
      name: "Sloane Stevens",
      email: "sstevens@tennis.org",
      role: "Admin",
      status: "pending",
    },
    {
      id: 19,
      name: "Reese Witherspoon",
      email: "rwitherspoon@legal.com",
      role: "Editor",
      status: "active",
    },
    {
      id: 20,
      name: "Hayden Pan",
      email: "hpan@hero.io",
      role: "Viewer",
      status: "inactive",
    },
    {
      id: 21,
      name: "Emerson Lake",
      email: "elake@prog.net",
      role: "Admin",
      status: "active",
    },
    {
      id: 22,
      name: "Charlie Day",
      email: "cday@sunny.phl",
      role: "Editor",
      status: "pending",
    },
    {
      id: 23,
      name: "Finley Scott",
      email: "fscott@author.uk",
      role: "Viewer",
      status: "active",
    },
    {
      id: 24,
      name: "Justice Smith",
      role: "Admin",
      email: "jsmith@detective.com",
      status: "active",
    },
    {
      id: 25,
      name: "Kiran Rao",
      email: "krao@film.in",
      role: "Editor",
      status: "inactive",
    },
    {
      id: 26,
      name: "Luca Moretti",
      email: "lmoretti@design.it",
      role: "Viewer",
      status: "pending",
    },
    {
      id: 27,
      name: "Noa Tishby",
      email: "ntishby@advocacy.org",
      role: "Admin",
      status: "active",
    },
    {
      id: 28,
      name: "Phoenix Wright",
      email: "pwright@law.jp",
      role: "Editor",
      status: "active",
    },
    {
      id: 29,
      name: "River Song",
      email: "rsong@tardis.blue",
      role: "Viewer",
      status: "pending",
    },
    {
      id: 30,
      name: "Sage Miller",
      email: "smiller@bakery.com",
      role: "Admin",
      status: "inactive",
    },
    {
      id: 31,
      name: "Tatum O'Neal",
      email: "toneal@oscar.com",
      role: "Editor",
      status: "active",
    },
    {
      id: 32,
      name: "Uriel Garcia",
      email: "ugarcia@export.mx",
      role: "Viewer",
      status: "active",
    },
    {
      id: 33,
      name: "Valerie June",
      email: "vjune@music.com",
      role: "Admin",
      status: "pending",
    },
    {
      id: 34,
      name: "Wren Woods",
      email: "wwoods@nature.org",
      role: "Editor",
      status: "inactive",
    },
    {
      id: 35,
      name: "Xander Cage",
      email: "xcage@triple.x",
      role: "Viewer",
      status: "active",
    },
    {
      id: 36,
      name: "Yael Grobglas",
      email: "ygrobglas@actor.il",
      role: "Admin",
      status: "active",
    },
    {
      id: 37,
      name: "Zion Williamson",
      email: "zwill@nba.com",
      role: "Editor",
      status: "pending",
    },
    {
      id: 38,
      name: "Arlo Guthrie",
      email: "aguthrie@folk.com",
      role: "Viewer",
      status: "active",
    },
    {
      id: 39,
      name: "Bowie Stardust",
      email: "zbowie@mars.com",
      role: "Admin",
      status: "inactive",
    },
    {
      id: 40,
      name: "Cleo Patra",
      email: "cpatra@history.eg",
      role: "Editor",
      status: "active",
    },
    {
      id: 41,
      name: "Dorian Gray",
      email: "dgray@portrait.uk",
      role: "Viewer",
      status: "pending",
    },
    {
      id: 42,
      name: "Elias Thorne",
      email: "ethorne@mystery.com",
      role: "Admin",
      status: "active",
    },
    {
      id: 43,
      name: "Flora Poste",
      email: "fposte@farm.co",
      role: "Editor",
      status: "active",
    },
    {
      id: 44,
      name: "Gideon Prewett",
      email: "gprewett@order.magic",
      role: "Viewer",
      status: "inactive",
    },
    {
      id: 45,
      name: "Hollis Brown",
      email: "hbrown@ballad.com",
      role: "Admin",
      status: "pending",
    },
    {
      id: 46,
      name: "Iris West",
      email: "iwest@centralcity.news",
      role: "Editor",
      status: "active",
    },
    {
      id: 47,
      name: "Jude Fawley",
      email: "jfawley@obscure.edu",
      role: "Viewer",
      status: "active",
    },
    {
      id: 48,
      name: "Kit Snicket",
      email: "ksnicket@vfd.org",
      role: "Admin",
      status: "pending",
    },
    {
      id: 49,
      name: "Lark Voorhies",
      email: "lvoorhies@saved.com",
      role: "Editor",
      status: "inactive",
    },
    {
      id: 50,
      name: "Milo Thatch",
      email: "mthatch@atlantis.exp",
      role: "Viewer",
      status: "active",
    },
    {
      id: 51,
      name: "Nico di Angelo",
      email: "nico@hades.gr",
      role: "Admin",
      status: "active",
    },
    {
      id: 52,
      name: "Olive Penderghast",
      email: "olive@easy.a",
      role: "Editor",
      status: "pending",
    },
  ],
  meta: {
    totalCount: 52,
    currentPage: 1,
    pageSize: 5,
  },
};
